from enum import Enum

class TokenType(Enum):
    INTEGER = 'INTEGER'
    PLUS = 'PLUS'
    MINUS = 'MINUS'
    MUL = 'MUL'
    DIV = 'DIV'
    LPAREN = 'LPAREN'
    RPAREN = 'RPAREN'
    LBRACE = 'LBRACE'
    RBRACE = 'RBRACE'
    EOF = 'EOF'
    MOD = 'MOD'
    POWER = 'POWER'
    GREATER = 'GREATER'
    INT = 'INT'
    RETURN = 'RETURN'
    SEMI = 'SEMI'
    IDENTIFIER = 'IDENTIFIER'
    ASSIGN = '='